# Generated by Django 3.2.1 on 2021-05-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ages',
        ),
    ]
