# Generated by Django 3.2.1 on 2021-05-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0002_remove_game_ages'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='min_age',
            field=models.IntegerField(default=21),
        ),
        migrations.AddField(
            model_name='game',
            name='release_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='time_to_play',
            field=models.IntegerField(default=0),
        ),
    ]
