# Generated by Django 3.2.1 on 2021-05-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapp', '0005_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ManyToManyField(through='raterapp.CategoryGame', to='raterapp.Category'),
        ),
    ]
